### ISSUE TITLE
Live Example not working

### ISSUE THREAD

**Issue by matthiasg** [angie-party/Thinc#2]
It seems the live example is ES6 and not compiled. http://angie-party.github.io/Thinc/ causes unexpected strict word 'let'.

**Comment by devopsmariocom** [comment]
Hi,

thanks for your feedback. I totally forgot to mention that example is working ony in Google Chrome, as it suppose to run using NW.js which use chromium it doesn't have much sense for us to optimise it for other browsers.

Did updated Readme file to make it clear. If you want to participate and make example to run in "all" browsers fee free to open pull request :thumbsup:

Mario

**Comment by matthiasg** [comment]
I did try in chrome.. The local version when cloned is working but the live version linked it not.

**Comment by devopsmariocom** [comment]
Hmmm strange... according to compat table here https://kangax.github.io/compat-table/es6/ let is supported in CH 41 in strict mode so it should be ok. Please send me exact version of your browser and your os so I can try it by myslef.

Thanks

Mario

**Comment by matthiasg** [comment]
on my other pcs chrome 41 it works,so the other machine must be older.

**Comment by devopsmariocom** [comment]
I'm glad it's working.

Cheers

Mario
